# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale                   : "en-US"
title                    : "Eric Guldbrand"
title_separator          : "|"
name                     : "Eric Guldbrand"
description              : "Portfolio, blog and project repository of Eric Guldbrand, a computer science student, gamer and sci-fi/fantasy enthusiast."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eric.guldbrand.io" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name             : "Eric Guldbrand"
  avatar           : "/assets/images/20180331_eric_github-small.jpg"
  bio              : "Computer science student, gamer, hobby violinist, fantasy and sci-fi enthusiast."
  location         : "Gothenburg"
  email            : "ericgul@student.chalmers.se"

# Collections
collections:
  projects:
    output: true

# Defaults
defaults:
  - scope:
      path: "" # empty string means all files in project
    values:
      layout: "base-page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blogpost"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project-page"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Outputting
#permalink: /:categories/:title/
permalink: pretty
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Build settings
markdown: kramdown
sass:
  style: compressed
future: false

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
